### ISSUE TITLE
Highlight 'elseif'?

### ISSUE THREAD

**Issue by KingWebsites** [Banane9/notepadplusplus-twig#10]
Hi, thanks for the file.

Could you add 'elseif' to your list of highlighted syntax? I'm using in this way:
{% if *cond* %}
	do foo
{% elseif *cond* %}
	do bar
{% endif %}

Currently the 'elseif' text is not highlighted.

Cheers!

**Comment by Banane9** [comment]
Just seeing this now ... goddammit github XD
