### ISSUE TITLE
Can't inport in notepad++ v6.6.9

### ISSUE THREAD

**Issue by Pavinati** [Banane9/notepadplusplus-twig#11]
When i click inport and select twig.xml, the dialog closes with the message : "Failed to import" i don't know how to provide you more information regarding that issue.

Tested in
- windows 7 64bit
- notepad++ v6.6.9

**Comment by shermdog** [comment]
It worked for me with notepad++ 6.6.9 on Windows 8.1
I'd check to make sure you downloaded and saved the XML properly.

**Comment by ragobo** [comment]
hi I have notepad+ 6.7.7 version... when I follow the steps you have written, it throws an error "import failed" let me know how to solve this issue

**Comment by Banane9** [comment]
As @shermdog pointed out, make sure you downloaded the .xml file properly.

**Comment by ragobo** [comment]
ofcourse! as you can see from the screenshot I donwloaded properly and you can also see the error
![twig](https://cloud.githubusercontent.com/assets/12249027/7472484/3fb2bc6c-f333-11e4-967c-5e3b9898cb25.jpg)

**Comment by Banane9** [comment]
Could you show a picture of the opened file?

**Comment by ACSiiWeb** [comment]
Just to be sure : Right Clic on this link > Save As

Then Import downloaded File

https://github.com/Banane9/notepadplusplus-twig/blob/master/Twig.xml

**Comment by Banane9** [comment]
No, this link:

https://raw.githubusercontent.com/Banane9/notepadplusplus-twig/master/Twig.xml

Otherwise you'll save github's rendering of the file (lots of html).
