### ISSUE TITLE
fail to import

### ISSUE THREAD

**Issue by ragobo** [Banane9/notepadplusplus-twig#12]
Hi,
I am using npp version 6.7.7 and when I try to import it says "fail to import". So I couldnt define twig as a highlighter in my npp. Looking for your helps
![twig](https://cloud.githubusercontent.com/assets/12249027/7470793/4969ca10-f320-11e4-924d-896037c8c594.jpg)

**Comment by ragobo** [comment]
ah ok... I got the point... I solved by directly copy and pasting the source of twig.xml thanks for your work! appreciated

**Comment by Banane9** [comment]
Thanks you and have fun :)

**Comment by klasseng** [comment]
OK, I can understand the copying of twig.xml source . . . where does it get pasted?

**Comment by klasseng** [comment]
Sorry, found answer on:
https://github.com/Banane9/notepadplusplus-twig/issues/11
