### ISSUE TITLE
Simple quote is always treated as an opening string

### ISSUE THREAD

**Issue by Masadow** [Banane9/notepadplusplus-twig#13]
As the example below shows

    <button class="btn subscribe col-md-offset-3">S'inscrire</button>

Starting from the simple quote, it is considered as a string declaration whereas it's just plain html right now.

**Comment by Banane9** [comment]
Well, sadly NP++ doesn't allow mixing formatings with custom language definitions like it does with php/html/js; so there's not much I can do about that.

**Comment by Banane9** [comment]
Added an alternative language def that sort of fixes this.

**Comment by Masadow** [comment]
Thanks ! :) Better than nothing
