### ISSUE TITLE
White backgrounds for dark Notepad++

### ISSUE THREAD

**Issue by bertoost** [Banane9/notepadplusplus-twig#14]
All the backgrounds for the syntax are set to white. This should be removed for dark configured Notepad++. Can it be transparent?

![image](https://cloud.githubusercontent.com/assets/398492/7882389/716a9210-060d-11e5-81f8-991cac1a428a.png)

**Comment by briosheje** [comment]
As far as I know no, this can't be transparent, what you can do, though, is "copying" the background color of your style (go to settings -> configure styles -> background -> more colours) 

![](http://i.imgur.com/T3R5NZ2.png)

Then save the color to your favorites:
![](http://i.imgur.com/gKMjqGB.png)

Then go to Language -> define your language -> select Twig and, in each of the four sections shown, edit each style setting the desired background.

From the "zenburn" I've been able to come up with something like that:

![](http://i.imgur.com/89P01Js.png)

**Comment by roopezero** [comment]
Actually, by right-clicking the background color, Notepad++ (I'm using v6.8.8) lets you to set the color transparent.
