### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by bojris** [Banane9/notepadplusplus-twig#17]
After going to Define your language -> Import and selecting either Twig.xml or TwigAlternative.xml I get 'Fail to import.' box.
Kindly offer a solution.
Thanks.

Notepad++ v6.9.1
 
![capture](https://cloud.githubusercontent.com/assets/17053341/14501994/20db5788-0177-11e6-8aca-9833c76cf242.PNG)
![capture](https://cloud.githubusercontent.com/assets/17053341/14502014/3badf606-0177-11e6-9c81-0d9002c187ab.PNG)

**Comment by Banane9** [comment]
As per issue #11, use this link to save the file:
https://raw.githubusercontent.com/Banane9/notepadplusplus-twig/master/Twig.xml
