### ISSUE TITLE
Notepad++ 7.1 failed to import twig.xml

### ISSUE THREAD

**Issue by tonydebling** [Banane9/notepadplusplus-twig#19]
Followed your instructions but Notepad++ gave a "failed to import XML" error alert when I tried to import both the twig.xml and the twigalternative.xml files. Not sure if this is the right place to report this.

**Comment by Banane9** [comment]
What's your twig.xml look like?

**Comment by tonydebling** [comment]
Sorry, my mistake. I just saved the link to twig.xml, not the file.
