### ISSUE TITLE
Can't see with dark screens

### ISSUE THREAD

**Issue by Grynn07** [Banane9/notepadplusplus-twig#22]
This was really useful, thank you! 

I like to use a darker background screen, especially the Monokai theme, which reminds me of Sublime text's theme, and so I was unable to see the comments at all. 

I took your alternative code and redid some of the colors for those wanting a darker background, feel free to include it in your original file, or change up the colors if you think  others would be better. This is my first time doing it, so it was a learning experience as much as anything else. 

Thanks again!
[Twig.zip](https://github.com/Banane9/notepadplusplus-twig/files/1345703/Twig.zip)

**Comment by Banane9** [comment]
Pull Request #23 just added a dark theme file [here](https://github.com/Banane9/notepadplusplus-twig/blob/master/TwigDark.xml)
